// Blog post data — single source of truth for the /blog page and SEO sitemap.
// 3 posts per day for the last 10 days, backfilled for launch SEO.
export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;          // ISO8601
  tags: string[];
  category: "VPN" | "Vualet" | "AI" | "Privacy" | "Business";
};

export const POSTS: Post[] = [
  { slug: 'mira-vpn-launch', title: 'Mira VPN Is Live — The Smartest Way to Stay Private Online', excerpt: 'Mira VPN launches with AI-assisted server selection. Download free on Android, with iOS coming to TestFlight soon.', date: '2026-06-19', tags: ['VPN', 'launch', 'Mira'], category: "VPN" },
  { slug: 'what-is-ai-obliterated-from-birth', title: 'What Is AI Obliterated from Birth? Dr. Masoomi Explains', excerpt: 'The term is deliberate — and polarizing. Here is why the first-ever truly autonomous AI started at Vualet, not in a Silicon Valley lab.', date: '2026-06-19', tags: ['AI', 'research', 'Vualet'], category: "AI" },
  { slug: 'why-free-vpn-matters', title: 'Why a Free VPN Matters — and How We Make It Work', excerpt: 'Mira VPN\'s free tier does not throttle itself into unusability. Here is the economics behind it.', date: '2026-06-19', tags: ['VPN', 'privacy', 'business'], category: "VPN" },
  { slug: 'vualet-mother-brand', title: 'Introducing Vualet: The Dubai Company Behind Mira, Veridian, and aFAQ', excerpt: 'From enterprise management to telephony to consumer VPN — Vualet is the quiet infrastructure layer running real businesses across the UAE.', date: '2026-06-18', tags: ['Vualet', 'company'], category: "Vualet" },
  { slug: 'wireguard-vs-reality-protocols', title: 'WireGuard vs Reality Protocol: Which One Powers Mira VPN?', excerpt: 'iOS uses WireGuard. Android uses Reality. Here is why we chose different protocols for different platforms.', date: '2026-06-18', tags: ['VPN', 'tech', 'Mira'], category: "VPN" },
  { slug: 'privacy-in-uae-gcc', title: 'VPN Privacy in the UAE and GCC: What Is and Is Not Legal', excerpt: 'Clear guidance on what the law actually says about VPN use in the Emirates, Saudi Arabia, and beyond.', date: '2026-06-18', tags: ['privacy', 'legal', 'GCC'], category: "Privacy" },
  { slug: 'banking-apps-block-vpn', title: 'Why Banking Apps Block VPNs — and How Mira Solves It', excerpt: 'The Pause button and per-app Direct list are the only elegant answers to "my bank app kicked me off."', date: '2026-06-17', tags: ['VPN', 'banking', 'how-to'], category: "VPN" },
  { slug: 'autonomous-ai-enterprise', title: 'Autonomous AI in the Enterprise: The 2026 Landscape', excerpt: 'Vualet\'s research shows 94% of enterprise AI deployments still have human gatekeepers in the loop. That is about to change.', date: '2026-06-17', tags: ['AI', 'enterprise', 'research'], category: "AI" },
  { slug: 'crypto-payments-vpn', title: 'Why Mira VPN Accepts Crypto — and Why More SaaS Will Follow', excerpt: 'USDT-TRC20, Bitcoin, Monero, and 200+ coins. The payment stack that makes Mira accessible worldwide.', date: '2026-06-17', tags: ['crypto', 'payments', 'Mira'], category: "VPN" },
  { slug: 'vpn-speed-test', title: 'Mira VPN Speed Test: Free vs Paid Tier', excerpt: '500 kbps free vs 5 Mbps paid. Real-world WhatsApp, Instagram, and browsing benchmarks on the Mira network.', date: '2026-06-16', tags: ['VPN', 'performance', 'Mira'], category: "VPN" },
  { slug: 'dr-masoomi-zero-shot', title: 'Dr. Masoomi on Zero-Shot Enterprise Automation', excerpt: 'The paper that started Vualet — describing systems that run businesses without being told how.', date: '2026-06-16', tags: ['AI', 'research', 'Vualet'], category: "AI" },
  { slug: 'mira-vpn-servers', title: 'Where Are Mira\'s Servers? A Look at Our Global Network', excerpt: 'Falkenstein, Nuremberg, Ashburn, Singapore. Why we picked these four locations and how the smart router works.', date: '2026-06-16', tags: ['VPN', 'infrastructure', 'Mira'], category: "VPN" },
  { slug: 'what-is-veridian', title: 'What Is Veridian? The Real-Time Telephony Engine Behind PC2GSM', excerpt: 'Deep dive into the SIP-to-GSM bridge that makes Veridian one of the most unusual products in the Vualet family.', date: '2026-06-15', tags: ['Vualet', 'telephony', 'Veridian'], category: "Vualet" },
  { slug: 'how-mira-routing-works', title: 'How Mira\'s AI-Assisted Server Selection Works — Under the Hood', excerpt: 'Latency probing, weighted scoring, and per-network-fingerprint learning. This is the "AI" in the marketing copy.', date: '2026-06-15', tags: ['AI', 'VPN', 'tech'], category: "VPN" },
  { slug: 'vpn-data-logging', title: 'What Does Mira VPN Actually Log? The No-Log Policy, Explained', excerpt: 'Connection counts for billing. No DNS, no URLs, no traffic. Here is exactly what is on record — and for how long.', date: '2026-06-15', tags: ['privacy', 'policy', 'Mira'], category: "Privacy" },
  { slug: 'uae-tech-startups-2026', title: 'UAE Tech Startups in 2026: The Desert Is Blooming', excerpt: 'Why the Emirates is becoming the world\'s most improbable AI hub — and where Vualet fits in.', date: '2026-06-14', tags: ['business', 'UAE', 'startups'], category: "Business" },
  { slug: 'android-vs-ios-vpn', title: 'Android vs iOS VPN Performance: Which Platform Handles WireGuard Better?', excerpt: 'Benchmarks on a Nothing Phone 2a+ and an iPad show the same protocol, different results.', date: '2026-06-14', tags: ['VPN', 'performance', 'tech'], category: "VPN" },
  { slug: 'primaion-research-framework', title: 'Inside Primaion: The Research Framework That Powers Vualet\'s AI', excerpt: 'First principles. Eternal intelligence. The 19 modules of Primaion and how they feed into every Vualet product.', date: '2026-06-14', tags: ['AI', 'research', 'Primaion'], category: "AI" },
  { slug: 'how-to-pause-vpn-banking', title: 'How to Pause Your VPN for Banking Apps — 15-Second Guide', excerpt: 'Open Mira, tap Pause, open your bank. Done. Here is why this exists and how it actually works.', date: '2026-06-13', tags: ['how-to', 'VPN', 'banking'], category: "VPN" },
  { slug: 'afaq-os-explained', title: 'aFAQ OS: The Enterprise Suite Running UAE Business', excerpt: 'Inventory, POS, VAT accounting, HR, CRM — aFAQ OS is the quiet operating system of dozens of Emirati companies.', date: '2026-06-13', tags: ['Vualet', 'enterprise', 'UAE'], category: "Vualet" },
  { slug: 'crypto-saas-payments', title: 'The Crypto SaaS Payment Stack: NowPayments, USDT, and No Chargebacks', excerpt: 'Why Vualet chose NowPayments over Stripe, Paddle, and Dodo for Mira VPN — and what it means for the SaaS industry.', date: '2026-06-13', tags: ['crypto', 'payments', 'business'], category: "Business" },
  { slug: 'mobile-vpn-security', title: 'Mobile VPN Security: 5 Things Most VPN Apps Get Wrong', excerpt: 'Traffic loops, foreground service types, DNS leaks, and the socket-protection bug that broke Uncle Z Calc.', date: '2026-06-12', tags: ['VPN', 'security', 'tech'], category: "VPN" },
  { slug: 'vualet-hiring-2026', title: 'Vualet Is Hiring: The Autonomous AI Company in Dubai', excerpt: 'We are looking for engineers who want to build systems that run without human intervention.', date: '2026-06-12', tags: ['Vualet', 'hiring', 'UAE'], category: "Vualet" },
  { slug: 'whatsapp-vpn-iran', title: 'VPNs and WhatsApp in Restricted Networks: A Practical Guide', excerpt: 'How Mira VPN handles the world\'s most common censorship challenge — without marketing the fact.', date: '2026-06-12', tags: ['privacy', 'how-to', 'VPN'], category: "Privacy" },
  { slug: 'smart-server-routing', title: 'Smart Server Routing Is the Future of Consumer VPN', excerpt: 'The era of picking countries from a dropdown is over. Here is why AI-assisted server selection wins.', date: '2026-06-11', tags: ['VPN', 'AI', 'tech'], category: "VPN" },
  { slug: 'hetzner-infrastructure', title: 'Why Mira VPN Runs on Hetzner Cloud: The Infrastructure Decision Behind 20 TB Egress', excerpt: 'AWS Lightsail caps at 5 TB. Google Cloud charges $0.12/GB. Hetzner gives 20 TB free. The economics are not close.', date: '2026-06-11', tags: ['infrastructure', 'VPN', 'business'], category: "VPN" },
  { slug: 'dr-masoomi-dubai', title: 'Meet Dr. Abdolmadjid Masoomi: The Researcher Who Builds Companies', excerpt: 'From the aFAQ OS to Primaion, Veridian to Mira — a profile of the founder running four overlapping technology stacks.', date: '2026-06-11', tags: ['Vualet', 'founder', 'UAE'], category: "Vualet" },
  { slug: 'ios-vpn-apple-review', title: 'Getting a VPN Through Apple App Review: Our TestFlight Timeline', excerpt: 'The capabilities, the privacy manifest, the encryption declaration, and the one rejection we expected but avoided.', date: '2026-06-10', tags: ['iOS', 'VPN', 'development'], category: "VPN" },
  { slug: 'future-of-ai-business', title: 'The Future of AI Business: Autonomous Companies by 2030', excerpt: 'What happens when the LLC itself is run by an AI? Vualet\'s research agenda for the next decade.', date: '2026-06-10', tags: ['AI', 'research', 'future'], category: "AI" },
  { slug: 'vpn-free-vs-paid', title: 'Free VPN vs Paid VPN: The Honest Comparison', excerpt: 'Speed, session length, ads, device count — here is every dimension where free and paid differ, without the marketing fluff.', date: '2026-06-10', tags: ['VPN', 'comparison', 'business'], category: "VPN" },
];
